name       : claws-mail
version    : 3.14.1
release    : 1
source     :
    - http://www.claws-mail.org//releases/claws-mail-3.14.1.tar.xz : b79a1dc04f0b3d1f693e84d7fa7282f140fb5280179281445a8b954ce423c335
license    : GPL-3.0
component  : network.mail
summary    : A GTK+ based, lightweight, and fast e-mail client
description: |
    A GTK+ based, lightweight, and fast e-mail client
builddeps  :
    - pkgconfig(enchant)
    - pkgconfig(gtk+-2.0)
    - pkgconfig(gnutls)
    - pkgconfig(libcanberra-gtk)
    - pkgconfig(libgdata)
    - pkgconfig(libnotify)
    - pkgconfig(NetworkManager)
    - pkgconfig(webkitgtk-3.0)
    - gnupg
    - gpgme-devel
    - libassuan-devel
    - libetpan-devel
    - openldap-devel
setup      : |
    %configure --disable-static
build      : |
    %make
install    : |
    %make_install
