name       : claws-mail
version    : 3.17.5
release    : 19
source     :
    - https://www.claws-mail.org/releases/claws-mail-3.17.5.tar.xz : daced25bfc2ab5b3f9ac2762b091ca3aede50da23e694d338dff1f066bab59be
license    : GPL-3.0-or-later
component  : network.mail
summary    : A GTK+ based, lightweight, and fast e-mail client
description: |
    A GTK+ based, lightweight, and fast e-mail client
builddeps  :
    - pkgconfig(dbus-glib-1)
    - pkgconfig(enchant-2)
    - pkgconfig(gnutls)
    - pkgconfig(gtk+-2.0)
    - pkgconfig(libarchive)
    - pkgconfig(libcanberra-gtk)
    - pkgconfig(libcurl)
    - pkgconfig(libical)
    - pkgconfig(libgdata)
    - pkgconfig(libnm)
    - pkgconfig(libnotify)
    - pkgconfig(librsvg-2.0)
    - pkgconfig(sm)
    - pkgconfig(poppler)
    - pkgconfig(pygtk-2.0)
    - gnupg
    - gpgme-devel
    - libassuan-devel
    - libetpan-devel
    - openldap-devel
    - perl
rundeps    :
    - perl
setup      : |
    %configure --disable-static \
        --enable-libsm \
        --enable-svg
build      : |
    %make
install    : |
    %make_install
