name       : claws-mail
version    : 3.16.0
release    : 10
source     :
    - http://www.claws-mail.org//releases/claws-mail-3.16.0.tar.xz : c212133d3d962129d8c7995c1c7d973faef2a8914481c0c74578217bf4c897ab
license    : GPL-3.0-or-later
component  : network.mail
summary    : A GTK+ based, lightweight, and fast e-mail client
description: |
    A GTK+ based, lightweight, and fast e-mail client
builddeps  :
    - pkgconfig(NetworkManager)
    - pkgconfig(dbus-glib-1)
    - pkgconfig(enchant)
    - pkgconfig(gnutls)
    - pkgconfig(gtk+-2.0)
    - pkgconfig(libarchive)
    - pkgconfig(libcanberra-gtk)
    - pkgconfig(libgdata)
    - pkgconfig(libnotify)
    - pkgconfig(poppler)
    - pkgconfig(pygtk-2.0)
    - pkgconfig(webkitgtk-3.0)
    - gnupg
    - gpgme-devel
    - libassuan-devel
    - libetpan-devel
    - openldap-devel
setup      : |
    %configure --disable-static
build      : |
    %make
install    : |
    %make_install
