name       : claws-mail
version    : 3.15.1
release    : 7
source     :
    - http://www.claws-mail.org//releases/claws-mail-3.15.1.tar.xz : 8d093c2f32db863c1141d56e35424c04ee48fe5d6adf4c7f349f647fa3149542
license    : GPL-3.0
component  : network.mail
summary    : A GTK+ based, lightweight, and fast e-mail client
description: |
    A GTK+ based, lightweight, and fast e-mail client
builddeps  :
    - pkgconfig(dbus-glib-1)
    - pkgconfig(enchant)
    - pkgconfig(gtk+-2.0)
    - pkgconfig(gnutls)
    - pkgconfig(libarchive)
    - pkgconfig(libcanberra-gtk)
    - pkgconfig(libgdata)
    - pkgconfig(libnotify)
    - pkgconfig(poppler)
    - pkgconfig(pygtk-2.0)
    - pkgconfig(NetworkManager)
    - pkgconfig(webkitgtk-3.0)
    - gnupg
    - gpgme-devel
    - libassuan-devel
    - libetpan-devel
    - openldap-devel
setup      : |
    %configure --disable-static
build      : |
    %make
install    : |
    %make_install
