name       : claws-mail
version    : 3.15.0
release    : 4
source     :
    - http://www.claws-mail.org//releases/claws-mail-3.15.0.tar.xz : 4e4d2d0d43f8ae3d4623408612f5979e9a697ccbc12038b80dd27802e868dc2e
license    : GPL-3.0
component  : network.mail
summary    : A GTK+ based, lightweight, and fast e-mail client
description: |
    A GTK+ based, lightweight, and fast e-mail client
builddeps  :
    - pkgconfig(dbus-glib-1)
    - pkgconfig(enchant)
    - pkgconfig(gtk+-2.0)
    - pkgconfig(gnutls)
    - pkgconfig(libarchive)
    - pkgconfig(libcanberra-gtk)
    - pkgconfig(libgdata)
    - pkgconfig(libnotify)
    - pkgconfig(poppler)
    - pkgconfig(pygtk-2.0)
    - pkgconfig(NetworkManager)
    - pkgconfig(webkitgtk-3.0)
    - gnupg
    - gpgme-devel
    - libassuan-devel
    - libetpan-devel
    - openldap-devel
setup      : |
    %configure --disable-static
build      : |
    %make
install    : |
    %make_install
