name       : claws-mail
version    : 4.0.0
release    : 29
source     :
    - https://www.claws-mail.org/releases/claws-mail-4.0.0.tar.xz : 4af2bd26a5d91eacb2a9c09f67a6a46c2222b40817c1f525dc050bdc7b0ee475
license    : GPL-3.0-or-later
component  : network.mail
summary    : A GTK+ based, lightweight, and fast e-mail client
description: |
    A GTK+ based, lightweight, and fast e-mail client
builddeps  :
    - pkgconfig(dbus-glib-1)
    - pkgconfig(enchant-2)
    - pkgconfig(gnutls)
    - pkgconfig(gpgme)
    - pkgconfig(gtk+-3.0)
    - pkgconfig(libarchive)
    - pkgconfig(libassuan)
    - pkgconfig(libcanberra-gtk)
    - pkgconfig(libcurl)
    - pkgconfig(libical)
    - pkgconfig(libetpan)
    - pkgconfig(libgdata)
    - pkgconfig(libnm)
    - pkgconfig(libnotify)
    - pkgconfig(librsvg-2.0)
    - pkgconfig(sm)
    - pkgconfig(poppler)
    - pkgconfig(pygobject-3.0)
    - pkgconfig(python3)
    - gnupg
    - openldap-devel
    - perl
rundeps    :
    - perl
setup      : |
    # I have no idea why this is needed. `configure` should have received this flag from pkg-config.
    export LIBETPAN_LIBS='-letpan'
    %configure \
        --disable-static \
        --enable-libsm \
        --enable-svg \
        --disable-bsfilter-plugin \
        --enable-crash-dialog
build      : |
    %make
install    : |
    %make_install
